name: Build, test and upload coverage, run E2E tests

on:
  workflow_dispatch:
  push:
    branches:
      - v2

permissions:
  id-token: write

jobs:
  e2e:
    uses: ./.github/workflows/build_test_coverage.yml
    with:
      e2e: true
    secrets:
      token: ${{ secrets.API_KEY }}
